---
- name: Example playbook
  hosts: all
  become: true
  become_method: sudo 
  tasks:
  - name: Install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
    - apache2
    ignore_errors: true

        
        
...