---  
- name: File playbook
  hosts: all
  become: true
  become_method: sudo 
  tasks:
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /etc/foo.conf
      owner: ec2-user
      group: ec2-user
      mode: '0644'
      state: touch


  - name: Recursively change ownership of a directory
    ansible.builtin.file:
      path: /etc/foo
      state: directory
      recurse: yes
      owner: foo
      group: foo

