---
- name: Ensure group "devops" exists
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04" 
    ansible.builtin.group:
      name: devops
      state: present
  - name: Add users
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04" 
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
    - tom
  - name: adding existing user '{{ item }}' to group devops
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04" 
    user:
       name: "{{ item }}"
       groups: devops
       append: yes
    with_items:
     - Bob
     - ben
     - lisa
     - katty
     - tom