---
- name: task1
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: "{{ item }}"
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
    with_items:
    - Bob
    - ben
    - lisa
    - katty
  

  - name: Download url for Bob
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/Bob

  - name: Download url for ben
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/ben

  - name: Download url for lisa
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/lisa

  - name: Download url for katty
    ignore_errors: true
    ansible.builtin.get_url:
      url: https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv
      dest: /home/katty

  - name: Install MariaDB server 
    when: 
    - ansible_facts['distribution'] == "Ubuntu" 
    - ansible_facts['distribution_version'] == "16.04"
    ansible.builtin.package:
      name: apache2
      state: present
    notify: Restart MariaDB


  handlers:
  - name: Restart webserver Ubuntu
    when: 
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
    systemd:
      name: apache2
      state: restarted


    

    
      
