---
- name: Install wordpress
  hosts: all
  become: true
  become_method: sudo 
  vars:
    wordpress_version: "4.0.32"
    php_version: "5.4.16"



  tasks:
  - name: Install prerequisites 
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - php-{{ php_version }}
    - php-mysql-{{ php_version }}
    - telnet
    notify: Start webserver

  - name: Get wordpress 
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    get_url:
      url: https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz
      dest: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      mode: '0440'



  - name: Unzip Wordpress
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    unarchive:
      src: /tmp/wordpress-{{ wordpress_version }}.tar.gz
      dest: /var/www/html/
      remote_src: true


  - name: Move wordpress
    when: 
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    shell: "cp -r  /var/www/html/wordpress/*   /var/www/html || exit 0"
    ignore_errors: true

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: testfile
      dest: /etc/testfile.conf
      mode: '0644'


