---
- name: builds VPC
  hosts: localhost
  gather_facts: no
  vars_files:
    envs/dev.yaml
  tasks:
  - name: create a VPC with dedicated tenancy and a couple of tags
    amazon.aws.ec2_vpc_net:
      name: Module_dev2
      cidr_block: "{{ vpc_cidr_block }}"
      region: "{{ region }}"
      tags: "{{ aws_tags }}"
      tenancy: default
    register: Ansible #It saves how vpc was created into Ansible